import type { Metadata } from "next";
import {  Nunito } from "next/font/google";
import "./globals.css";
import Logo from "./components/logo";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meta Diaria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`px-10 py-5 ${inter.className}`}>
      <Logo />
        {children}
      </body>
    </html>
  );
}
